idaholab/TMAP8

doc/config.yml
doc/content/getting_started/installation.md
doc/content/getting_started/user_notes.md
doc/content/getting_started/using_tmap8.md
doc/content/index.md
doc/content/source/nodal_kernels/TrappingNodalKernel.md
doc/content/syntax/index.md

@singhgp4321 @lindsayad here are the new getting started documentation pages I was thinking of when meeting with the INL Fusion Safety team. I also cleaned up the homepage and moved Alex's Scaling notes to a "User Notes" page - perhaps we can keep this page updated with good usage guidelines in the future? 
Closes #19

Add TMAP8 getting started documentation and clean-up homepage

---

doc/content/getting_started/installation.md
src/kernels/ADMatCoupledDefectAnnihilation.C

@simopier I noticed a typo in a header that I missed in #36, so I figured while I was here I'll add those update instructions you requested in #33. Care to review?

Add update instructions and fixup source header

---

doc/config.yml

@lindsayad missed this one since we don't test the SQA documentation build by default on PRs. 
Refs #38

Fixup broken SQA doc build

---

doc/content/getting_started/installation.md

Use a tip alert for this and note that is is an optional feature of the chemical reactions module. After #40, thought this might be useful for new users to know about.

Add thermochimica to installation instructions

---

README.md
include/auxkernels/EmptySitesAux.h
include/base/TMAPApp.h
include/bcs/EquilibriumBC.h
include/kernels/ADMatCoupledDefectAnnihilation.h
include/kernels/ADMatReactionFlexible.h
include/kernels/ScaledCoupledTimeDerivative.h
include/nodal_kernels/ReleasingNodalKernel.h
include/nodal_kernels/TrappingNodalKernel.h
include/postprocessors/PressureReleaseFluxIntegral.h
include/scalar_kernels/EnclosureSinkScalarKernel.h
src/auxkernels/EmptySitesAux.C
src/base/TMAPApp.C
src/bcs/EquilibriumBC.C
src/kernels/ADMatCoupledDefectAnnihilation.C
src/kernels/ADMatReactionFlexible.C
src/kernels/ScaledCoupledTimeDerivative.C
src/main.C
src/nodal_kernels/ReleasingNodalKernel.C
src/nodal_kernels/TrappingNodalKernel.C
src/postprocessors/PressureReleaseFluxIntegral.C
src/scalar_kernels/EnclosureSinkScalarKernel.C
test/include/base/TMAPTestApp.h
test/src/base/TMAPTestApp.C
unit/src/SampleTest.C
unit/src/main.C

Update copyright year to 2023

---

doc/content/source/bcs/EquilibriumBC.md
include/bcs/EquilibriumBC.h
src/bcs/EquilibriumBC.C
test/tests/ver-1a/ver-1a.i

Updating the EquilibriumBC

---

.gitignore
doc/content/source/materials/SolubilityRatioMaterial.md
doc/sqa_reports.yml
src/bcs/EquilibriumBC.C
src/nodal_kernels/ReleasingNodalKernel.C
src/nodal_kernels/TrappingNodalKernel.C
src/scalar_kernels/EnclosureSinkScalarKernel.C

Application-level reports now pass and will be changed to an error for future PRs. 
Closes #62

Add documentation and class descriptions

---

doc/sqa_reports.yml

Fixup deprecated SQA label for RTM document

---

src/base/TMAP8App.C
src/main.C
test/src/base/TMAP8TestApp.C
unit/src/main.C

Use new Moose::main, update registration

---

NOTICE.txt
README.md
include/auxkernels/EmptySitesAux.h
include/base/TMAP8App.h
include/bcs/EquilibriumBC.h
include/interfacekernels/InterfaceSorptionSievert.h
include/kernels/ADMatCoupledDefectAnnihilation.h
include/kernels/ADMatReactionFlexible.h
include/kernels/ScaledCoupledTimeDerivative.h
include/nodal_kernels/ReleasingNodalKernel.h
include/nodal_kernels/TrappingNodalKernel.h
include/postprocessors/PressureReleaseFluxIntegral.h
include/scalar_kernels/EnclosureSinkScalarKernel.h
include/utils/PhysicalConstants.h
src/auxkernels/EmptySitesAux.C
src/base/TMAP8App.C
src/bcs/EquilibriumBC.C
src/interfacekernels/InterfaceSorptionSievert.C
src/kernels/ADMatCoupledDefectAnnihilation.C
src/kernels/ADMatReactionFlexible.C
src/kernels/ScaledCoupledTimeDerivative.C
src/main.C
src/nodal_kernels/ReleasingNodalKernel.C
src/nodal_kernels/TrappingNodalKernel.C
src/postprocessors/PressureReleaseFluxIntegral.C
src/scalar_kernels/EnclosureSinkScalarKernel.C
test/include/base/TMAP8TestApp.h
test/src/base/TMAP8TestApp.C
unit/src/SampleTest.C
unit/src/main.C

Noticed I hadn't done this yet. Requesting review from @simopier.
Ref #30

Update copyright year to 2024

---

README.md

Add a hyperlink to the INL served docs for TMAP8

---

doc/bibliography/bib.bib
doc/content/bib/tmap8.bib
doc/content/source/utils/PhysicalConstants.md
doc/content/syntax/index.md
doc/content/syntax/physical_constants_alert.md
doc/content/syntax/tmap_only.md

Create documentation for `PhysicalConstants`.

---

doc/config.yml
doc/content/getting_started/installation.md
doc/content/getting_started/using_tmap8.md

- Update config.yml to add links to important pages to header menu
- Update installation instructions for clarity
- Have users update on devel rather than main
- Update instructions to use TMAP8 to add link to examples
(Close. #95)

Update TMAP8 website

---

doc/content/examples/tmap_index.md
doc/content/getting_started/using_tmap8.md

Add symlink to fix doco

---

.coverage

Refs #93
The accompanying issue should not be closed until the CIVET recipes and infrastructure is also in. This file is OK with going in before that. 
CIVET recipes PR: idaholab/civet_recipes#1651

Add TMAP8 coverage configuration

---

doc/config.yml
doc/content/index.md
unit/Makefile

- Ignore duplicate bib entries from modules
- Add TMAP7 to V&V description
- Adjust MOOSE language and INL logo on home page
Refs #95
Used to test coverage recipes #93

Adjust documentation and test coverage checks

---

doc/content/verification/ver-list.md

Add SQA discussion in ver-list.md

---

doc/content/getting_started/installation.md

Update instructions to update TMAP8 and Conda

---

doc/config.yml
doc/content/sqa/index.md
doc/content/sqa/theory_manual.md
doc/content/sqa/tmap8_cci.md
doc/content/sqa/tmap8_far.md
doc/content/sqa/tmap8_rtm.md
doc/content/sqa/tmap8_scs.md
doc/content/sqa/tmap8_sdd.md
doc/content/sqa/tmap8_sll.md
doc/content/sqa/tmap8_srs.md
doc/content/sqa/tmap8_stp.md
doc/content/sqa/tmap8_vvr.md
doc/content/sqa/user_manual.md
doc/sqa_reports.yml

TMAP8 corrective action SQA

---

.gitattributes

Add TMAP8 gitattributes file

---

test/tests/kernels/ad_mat_coupled_annihilation/ad_mat_coupled_annihilation_test.i
test/tests/kernels/ad_mat_reaction_flexible/ad_mat_reaction_flexible_test.i
test/tests/val-2b/val-2b.i
test/tests/val-2b/val-2b_with_heatTransfer.i
test/tests/ver-1b/ver-1b.i
test/tests/ver-1d/ver-1d-diffusion.i
test/tests/ver-1d/ver-1d-trapping.i
test/tests/ver-1fa/ver-1fa.i
test/tests/ver-1g/ver-1g.i

Update input files to remove deprecated names

---

doc/config.yml
doc/content/getting_started/contributing.md
doc/content/getting_started/using_tmap8.md
doc/content/index.md

Add instructions to contribute to TMAP8

---

doc/content/verification_and_validation/index.md

refs idaholab/moose#24406
trying to fix this failure
https://civet.inl.gov/job/2374372/
this is fairly time sensitive, I'd like a moose devel merge for a customer

Make link tentatively more precise for SQA index,

---

test/tests/ver-1ja/ver-1ja.i

Fix depreciated input file

---

doc/content/source/interfacekernels/InterfaceSorption.md

Clean up broken format in Sorption documentation

---

doc/content/verification_and_validation/val-2b.md
doc/content/verification_and_validation/ver-1a.md
doc/content/verification_and_validation/ver-1b.md
doc/content/verification_and_validation/ver-1c.md
doc/content/verification_and_validation/ver-1d.md
doc/content/verification_and_validation/ver-1e.md
doc/content/verification_and_validation/ver-1fa.md
doc/content/verification_and_validation/ver-1fb.md
doc/content/verification_and_validation/ver-1fc.md
doc/content/verification_and_validation/ver-1fd.md
doc/content/verification_and_validation/ver-1g.md
doc/content/verification_and_validation/ver-1gc.md
doc/content/verification_and_validation/ver-1ha.md

Add the input section for all V&V documentation
(refs #150)

Add input section for V&V documentation

---

doc/content/source/utils/PhysicalConstants.md

Update the Boltzmann constant typo in PhysicalConstants.md

---

doc/content/verification_and_validation/val-2b.md
doc/content/verification_and_validation/ver-1a.md
doc/content/verification_and_validation/ver-1b.md
doc/content/verification_and_validation/ver-1d.md
doc/content/verification_and_validation/ver-1dc.md
doc/content/verification_and_validation/ver-1fa.md
doc/content/verification_and_validation/ver-1fb.md
doc/content/verification_and_validation/ver-1g.md
test/tests/val-2b/comparison_val-2b.py
test/tests/ver-1a/comparison_ver-1a.py
test/tests/ver-1b/comparison_ver-1b.py
test/tests/ver-1d/comparison_ver-1d.py
test/tests/ver-1fa/comparison_ver-1fa.py
test/tests/ver-1fb/comparison_ver-1fb.py
test/tests/ver-1g/comparison_ver-1g.py

Add RMSPE calculation on ver-1a, ver-1b, ver-1d, ver-1fa, ver-1fb, ver-1g, and val-2b.
(Ref. #166)

Add rmspe on the V&V cases missing it

---

test/tests/ver-1a/ver-1a.i

(Close. #211)
(Ref. #12)
(Ref. #123)

Update the units in input file of ver-1a

---

doc/content/getting_started/contributing.md

Update contributing instructions to fetch upstream before reset

---

doc/content/bib/articles_using_tmap8.bib
doc/content/bib/proceedings_using_tmap8.bib
doc/content/bib/tmap8.bib
doc/content/citing_tmap8.md

Fix references in documentation

---

doc/content/verification_and_validation/ver-1e.md

Fix typo in ver-1e.md

---

include/base/TMAP8App.h
src/base/TMAP8App.C
test/include/base/TMAP8TestApp.h
test/src/base/TMAP8TestApp.C

(Ref. idaholab/moose#30778)
(Close #271)

fix InputParameters for TMAP8

---

doc/content/bib/articles_using_tmap8.bib

Add new FED paper from T. Franklin

---

test/tests/ver-1fa/ver-1fa-physics.i
test/tests/ver-1g/ver-1g.i

Fix deprecated input files

---

test/tests/physics/exceptions/tests

refs https://github.com/idaholab/moose/pull/31395

Change error due to moose improvements

---

doc/config.yml
doc/content/verification_and_validation/val-2c.md
doc/content/verification_and_validation/val-2e.md
doc/content/verification_and_validation/val-2f.md

Add links to !include documentation in relevant TMAP8 V&V cases.
