doc/config.yml
doc/content/source/bcs/BinaryRecombinationBC.md
doc/content/source/bcs/DissociationFluxBC.md
doc/content/source/bcs/EquilibriumBC.md
doc/content/source/bcs/UnaryRecombinationBC.md
doc/content/source/kernels/BodyForceLM.md
doc/content/source/kernels/CoupledForceLM.md
doc/content/source/kernels/LMDiffusion.md
doc/content/source/kernels/RequirePositiveNCP.md
doc/content/source/kernels/ScaledCoupledTimeDerivative.md
doc/content/source/kernels/TimeDerivativeLM.md
doc/content/source/nodal_kernels/ReleasingNodalKernel.md
doc/content/source/nodal_kernels/TrappingNodalKernel.md
doc/content/source/postprocessors/PressureReleaseFluxIntegral.md
doc/content/source/scalar_kernels/EnclosureSinkScalarKernel.md
doc/content/sqa/index.md
doc/content/sqa/tmap_far.md
doc/content/sqa/tmap_rtm.md
doc/content/sqa/tmap_sdd.md
doc/content/sqa/tmap_srs.md
doc/content/sqa/tmap_stp.md
doc/content/sqa/tmap_vvr.md
doc/content/syntax/index.md
doc/content/syntax/tmap_only.md
doc/sqa_reports.yml
doc/sqa_tmap.yml

Still need to make an issue for this, but I implemented the basic infrastructure for MooseDocs and SQA last night in preparation for our meeting today. This PR: 
- Updates the MOOSE submodule
- Adds the SQA extension and YAML objects to generate a minimal website
- Adds basic stub documentation pages for existing TMAP8 objects
- Adds website links to SQA summary, a TMAP8-only documentation page, and a complete (TMAP + MOOSE) documentation page
Closes #6

SQA Infrastructure for TMAP8

---

test/tests/ncp-lms/README.md
test/tests/ncp-lms/diagonal-ncp-lm-nodal-enforcement.i

Closes #16
This change passes thread testing on my MacOS workstation, and doesn't seem to impact the results of any other test. @lindsayad do you happen to remember why you set `snes_max_linear_solve_fail` to zero here, and do you suggest an alternative change that might better fit the intent of the test?

Fixup PETSc options in diagonal-ncp-lm-nodal-enforcement input

---

doc/config.yml
doc/tutorial_config.yml
doc/workshops/tutorial/content/moose_intro.md
doc/workshops/tutorial/content/outro.md
doc/workshops/tutorial/content/tmap8_v_and_v.md
doc/workshops/tutorial/content/tmap8_vs_legacy.md
doc/workshops/tutorial/content/tutorial_getting_started.md
doc/workshops/tutorial/index.md

This PR adds initial infrastructure for a set of TMAP8 tutorial slides, based on the slide draft for the most recent TMAP8 tutorial sent to me by @simopier. 
The file structure set up here also allows for multiple kinds of workshops to be setup inside of the `doc/workshops` directory tree.
Closes #28

Add initial TMAP8 workshop/tutorial slides

---

include/bcs/EquilibriumBC.h
include/utils/PhysicalConstants.h
src/bcs/EquilibriumBC.C
src/interfacekernels/InterfaceSorptionSievert.C

- Create PhysicalConstants namespace
- Update existing classes to use PhysicalConstants.h
(Close #54)

Add PhysicalConstant namespace to use consistent values

---

doc/content/verification/ver-1c.md

This PR is a simple documentation fix in the ver1c case

Replaced solubility by diffusivity in the docs for ver1c

---

doc/content/verification/ver-1b.md

I noticed in the documentation of ver-1b the notes section was irrelevant to the problem since it has no traps.
It may be a copy paste from ver-1d.
Remove the irrelevant notes from ver-1b
Improved user experience when reading documentation

Remove irrelevant notes from documentation

---

doc/config.yml

Rather than using the MOOSE duplicate bibs file, single out the individual duplicates warned about during documentation builds. This needs to be done because `incropera2002` was introduced in #125, and this doesn't exist as a named duplicate in the main MOOSE file. 
Switch from including a duplicates list to only naming the ones TMAP8 warns about. 
No user-facing change. Removal of confusing documentation warning for `incropera2002`.

Remove duplicate bib warnings

---

doc/config.yml
doc/content/getting_started/hpc.md
doc/content/getting_started/installation.md

After lifting sections from our main getting started instructions as well as adapting @milljm's instructions from MOOSE on viewing results remotely, I have a first draft of TMAP8 HPC instructions. 
When we have regular containers, we can make another set of instructions for that instance. For now, let's provide manual ones. 
Refs #26

Add TMAP8 HPC instructions

---

doc/content/verification_and_validation/index.md
doc/sqa_tmap8.yml

Closes #152 
This also adds dependencies in the `sqa_tmap8.yml` file. These were missing, and resulted in technically incomplete SQA documentation.

Documentation adjustments to support FENIX

---

doc/content/getting_started/using_tmap8.md

- Update the typo, ~/projects/test/tests, with ~/projects/TMP8/test/tests
(Refs. #159)

Fix a typo in Documentation of "Using TMAP8"

---

doc/content/verification_and_validation/ver-1a.md
doc/content/verification_and_validation/ver-1ja.md

- Add "l" for \alpha_n equation of TMAP7 in ver1a, and update the first two equations of ver1ja
(Ref. #161)

Updating typos in equations

---

doc/content/getting_started/hpc.md

@simopier This set of instructions works using the `moose-dev` module on Sawtooth. Apptainer instructions for HPC were recently uploaded in the MOOSE repository, but these are very WIP. For now we'll stick with a manual build until we have something better. 
Refs #26

Update INL HPC directions

---

test/tests/ver-1b/tests
test/tests/ver-1c/tests
test/tests/ver-1d/tests
test/tests/ver-1e/tests
test/tests/ver-1fa/tests
test/tests/ver-1fb/tests
test/tests/ver-1g/tests
test/tests/ver-1gc/tests
test/tests/ver-1ha/tests

Make verification = '**.md' consistent across verification cases

---

test/tests/fuel-cycle/tests

Skip incompatible script testing in installs

---

test/tests/fuel-cycle/fuel_cycle_gui.py

Obtain values of input parameters at runtime as part of the workflow created by the 'buttonClick' method in the fuel_cycle_gui.py script. #closes #215

Address bug in fuel_cycle_gui.py script

---

doc/content/bib/articles_using_tmap8.bib
doc/content/bib/proceedings_using_tmap8.bib
doc/content/publications.md

Add PBNC paper to the documentation

---

doc/content/verification_and_validation/val-2a.md

This is fixing a small typo in a unit in the documentation for val-2a.
(Ref. #12)

Fix typo in val-2a

---

src/base/TMAP8App.C
test/tests/val-2d/val-2d.i

Remove legacy residual eval mode

---

doc/content/examples/divertor_monoblock/index.md

This was causing intermittent CI failures in other applications that use TMAP8
Closes #246

Set SQA link to be exact in divertor monoblock page

---

test/tests/val-2b/val-2b.i

We should not need to do that so something is probably up with Outputs/exodus/output_material_properties
and outputs = 'all' parameters. I posted on the moose PR that changed this
refs idaholab/moose#23550

Make sure all properties are output in case of a mix of 'output_material_properties'
